Comp120/config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'

  get 'home' => 'static_pages#home'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'data_visualization' => 'static_pages#data_visualization'

  get 'signup' => 'users#new'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'poll' => 'static_pages#polling'

  post 'resolve_micropost' => 'microposts#resolve_micropost'

  resources :users
  resources :microposts

  mount API::Base => '/api'
  mount GrapeSwaggerRails::Engine => '/apidoc'

end

Comp120/app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user, touch: true
  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :details, presence: true, length: { maximum: 1000 }
  validates :subject, presence: true, length: { maximum: 100 }
  validates :location, presence: true, length: { maximum: 250 }
  validates :open, presence: true
  validate :picture_size

  private

  def picture_size
  	if picture.size > 5.megabytes
  		errors.add(:picture, "should be less than 5MB")
  	end
  end
end

Comp120/app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
	before_action :logged_in_user, only: [:create]
	before_action :correct_user, only: [:update]

	def show
		@micropost = Micropost.find(params[:id])
		cookies[:lat] = @micropost.location_lat
		cookies[:lng] = @micropost.location_long
	end

	def create
		@micropost = current_user.microposts.build(micropost_params)
		@micropost.location_lat = cookies[:lat]
		@micropost.location_long = cookies[:lng]
		if @micropost.save
    		flash[:success] = "Your report has been submitted."
    		redirect_to @micropost
    	else
      		render 'shared/_micropost_form'
    	end
	end

	def update
		if @micropost.update(micropost_params)
			flash[:success] = "This report has been updated."
			redirect_to @micropost
		else
			flash[:danger] = "Unsuccessful update - please provide all of the necessary information."
			redirect_to @micropost
		end
	end

	def destroy
		@micropost = Micropost.find(params[:id])
		@micropost.destroy
		flash[:success] = "The report has been deleted."
		redirect_to root_url
	end

	def resolve_micropost
		@micropost = Micropost.find(params[:report_id])
		@micropost.update_attribute(:open, false)
		flash[:success] = "This report has been marked as resolved."
		redirect_to @micropost
	end

	private

	def micropost_params
		params.require(:micropost).permit(:details, :user_id, :picture, :subject, :location, :emergency, :open, :location_lat, :location_long, :report_id)
	end

	def correct_user
    @micropost = current_user.microposts.find_by(id: params[:id])
    redirect_to root_url if @micropost.nil?
  end
  
end

Comp120/app/helpers/microposts_helper.rb
module MicropostsHelper
end

Comp120/app/views/microposts/_micropost.html.erb
<tr>
  <td>
    <p><%= link_to micropost.subject, micropost %></p>
    <% if micropost.picture? %>
      <p>(photo available)</p>
    <% end %>
  </td>
  <td>
    <% if micropost.emergency == true %>
      <p class="red">EMERGENCY</p>
    <% else %>
      <p>Non-emergency</p>
    <% end %>
  </td>
  <td><%= time_ago_in_words(micropost.created_at)+" ago" %></td>
  <td>
    <% if micropost.open == true %>
      <p>Unresolved</p>
    <% else %>
      <p class="resolved">Resolved</p>
    <% end %> 
  </td>
</tr>

Comp120/app/views/microposts/show.html.erb
<% provide(:title, "View Report") %>

<div class="container-fluid">
  <div class="row-fluid">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-center">
      <% if current_user.admin == true %>
        <%= button_to 'Mark as Resolved', resolve_micropost_path(:report_id => @micropost.id), class: "btn btn-success", id: "newReportButton", :data => {:confirm => "This issue has been responded to and resolved?"} %>
        <br>
        <%= button_to "Delete Report", @micropost, method: :delete, :id => @micropost.id, class: "btn btn-danger", id: "newReportButton", :data => {:confirm => "Would you like to delete this report?"} %>
        <hr>
      <% end %>
      <h3><strong><em>Submitted by: </strong><%= link_to @micropost.user.first_name+" "+@micropost.user.last_name, user_path(@micropost.user.id) %></em></h3>
      <h3><strong>Subject: </strong><%= @micropost.subject %></h3>
      <h3><strong>Submitted: </strong><%= time_ago_in_words(@micropost.created_at) %> ago</h3>
      <% if @micropost.emergency == true %>
        <h2 class="red"><strong>EMERGENCY</strong></h2>
      <% else %>
        <h3>non-emergency</h3>
      <% end %>
      <h3><strong>Details: </strong><%= @micropost.details %></h3>
      <h3><strong>Location: </strong><%= @micropost.location %></h3>
      <% if @micropost.open == true %>
        <h3><strong>Status: </strong>Unresolved</h3>
      <% else %>
        <h3><strong>Status: </strong><span class="resolved">Resolved</span></h3>
      <% end %>
      <br>
      <%= image_tag @micropost.picture.url if @micropost.picture? %>
      <br>
      <br>
    </div>
  </div>
</div>

<div class="container-fluid">
  <div class="row-fluid">
    <div class="col-xs-10 col-sm-8 col-md-6 col-lg-6 col-xs-offset-1 col-sm-offset-2 col-md-offset-3 col-lg-offset-3 text-center">
      <div id="mapCanvas" style="width: 100%; height: 380px;"></div>
      <br>
    </div>
  </div>
</div>

<% if current_user?(@micropost.user) || current_user.admin == true %>
  <div id="newReportSlot" class="container-fluid">
    <div class="row-fluid">
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-center">
        <h1><strong>Edit Report:</strong></h1>
      </div>
    <div class="row-fluid">
      <div class="col-xs-10 col-sm-8 col-md-6 col-lg-6 col-xs-offset-1 col-sm-offset-2 col-md-offset-3 col-lg-offset-3 text-center">
        <%= form_for(@micropost, html: { multipart: true }) do |f| %>
          <%= render "shared/error_messages", object: f.object %>

          <br>
          <%= f.label :subject, "Subject:", class: "newReportLabel" %>
          <%= f.text_field :subject, class: "form-control" %>
          <br>
        
          <%= f.label :details, "Details:", class: "newReportLabel" %>
          <%= f.text_area :details, class: "form-control" %>
          <br>

          <%= f.label :location, "Location:", class: "newReportLabel" %>
          <%= f.text_field :location, class: "form-control" %>
          <br>

          <%= f.label :emergency, "Is this an Emergency?", class: "newReportLabel" %>
          <br>
          <%= f.check_box :emergency, id: "emergencyCheckBox" %>
          <br>
          <br>

          <div class="center">
            <%= f.label :picture, "Upload a photo: ", class: "newReportLabel" %>
            <div id="photoUpload"><%= f.file_field :picture, accept: "image/jpeg,image/gif,image/png" %></div>
            <br>
          </div>

          <%= f.submit "Submit", class: "btn btn-primary", id: "newReportButton" %>
          <br>
          <br>
        <% end %>
      </div>
    </div>
    </div>
  </div>
<% end %>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC0nKXA3huAMfcormU4i1h3ALXlwOFkz_E"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>

<script>

  if(navigator.geolocation) {
    navigator.geolocation.getCurrentPosition(function(position) {
      currentLocation = new google.maps.LatLng($.cookie("lat"), $.cookie("lng"));
      $.cookie("lat", position.coords.latitude);
      $.cookie("lng", position.coords.longitude);

      var properties = {
        center: currentLocation,
        zoom: 18,
        mapTypeId: google.maps.MapTypeId.SATELLITE
      };

      var map = new google.maps.Map(document.getElementById("mapCanvas"), properties);

      var marker = new google.maps.Marker({
        position: currentLocation,
        animation: google.maps.Animation.BOUNCE,
        draggable: true
      });

      marker.setMap(map);
    });
  }
  else {
    alert("Geolocation is not supported by your browser.");
  }

</script>