Comp120/config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'

  get 'home' => 'static_pages#home'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'data_visualization' => 'static_pages#data_visualization'

  get 'signup' => 'users#new'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'poll' => 'static_pages#polling'

  post 'resolve_micropost' => 'microposts#resolve_micropost'

  resources :users
  resources :microposts

  mount API::Base => '/api'
  mount GrapeSwaggerRails::Engine => '/apidoc'

end

Comp120/app/views/layouts/_footer.html.erb
<footer class="footer">
  <% if logged_in? %> 
   	  <p><%= link_to "DU-Incident Reporter", home_path %></p>
   <% else %>
   	  <p><%= link_to "DU-Incident Reporter", root_url %></p>
   <% end %>
  <nav>
    <ul>
    	<li><%= link_to "About", about_path %></li>
    	<li>|</li>
    	<li><%= link_to "Contact", contact_path %></li>
    	<li>|</li> 
      <li><%= link_to "API documentation", 'https://dutchessreporter.herokuapp.com//apidoc' %></li>
    </ul>
  </nav>
</footer>

Comp120/app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-inverse">
	  <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div id="navbar" class="collapse navbar-collapse text-center">
			  <ul class="nav navbar-nav">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Hello, "+current_user.first_name+" "+current_user.last_name+" |", current_user %></li>

				    <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Data Visualization", data_visualization_path %></li> 

            <% if current_user.admin? %>
              <li><%= link_to "Users", users_path %></li>
            <% end %>

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">My account <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li class="divider"></li>
                <li><%= link_to "Log out", logout_path, method: "delete" %></li>
              </ul>
            </li>
          </ul>
			  </ul>
      </div>
		</div>
	</nav>
</header>

Comp120/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  	<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  	</script>
<![endif]-->

Comp120/app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>

<head>
	<title>Incident Reporter | <%= yield(:title) %></title>
	<meta name="Dutchess University Incident Reporter" content="Beta">
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

	<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
	<%= render 'layouts/shim' %>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
</head>

<body>

<% if logged_in? %>
	<%= render 'layouts/header' %>
<% end %>

<%= render 'shared/logoSection' %>

<div class="text-center">
	<% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
</div>

<%= yield %>
<%= render 'layouts/footer' %>

</body>

</html>